### ISSUE TITLE
Error message when restoring backup

### ISSUE THREAD

**Issue by dplagge** [wal-g/wal-g#165] opened 2019-01-03 11:01 UTC
When I try to restore an backup with `wal-g backup-fetch` it fails after downloading most of the data:

    [...]
    /pg_wal
    /pg_xact
    /pg_xact/0000
    /postgresql-qa.conf
    /postgresql.auto.conf
    /postgresql.conf
    /server.crt
    /server.key
    2019/01/03 09:56:04 WAL-G does not support the file format '' in 'basebackups_005/base_000000010000004B000000CD/tar_partitions/'
    ExtractAll:
    github.com/wal-g/wal-g.tarHandler
            /home/travis/gopath/src/github.com/wal-g/wal-g/extract.go:97
    github.com/wal-g/wal-g.ExtractAll.func2.2
            /home/travis/gopath/src/github.com/wal-g/wal-g/extract.go:148
    runtime.goexit
            /home/travis/.gimme/versions/go1.8.7.linux.amd64/src/runtime/asm_amd64.s:2197

The restored directory seems to contain most of the data (having several GBs) but PostgreSQL does not successfully start up after placing a recovery.conf file into it.  The message is:

    postgres: could not find the database system
    Expected to find it in the directory "/postgresql/10/data",
    but could not open file "/postgresql/10/data/global/pg_control": No such file or directory

We use a Hitachi Content Platform as a S3 compatible service.

**Comment by x4m** [comment] 2019-01-03 11:20
Hi! It seems like there is some extraneous file in basebackups_005/base_000000010000004B000000CD/tar_partitions/
Can you list that folder?

**Comment by x4m** [comment] 2019-01-03 11:21
There must be only tar.%compressor, where %compressor is lz4, lzo, lzma or brotli

**Comment by dplagge** [comment] 2019-01-03 12:01
There are 15 files in that directory:

    part_001.tar.lz4
    part_002.tar.lz4
    [...]
    part_012.tar.lz4
    part_013.tar.lz4
    part_015.tar.lz4
    pg_control.tar.lz4

There seems to be no `part_014.tar.lz4`.

**Comment by x4m** [comment] 2019-01-03 12:52
hmmm, somehow storage pretend that 'basebackups_005/base_000000010000004B000000CD/tar_partitions/' is a file...
Did you use previous versions of WAL-G with this storage?

If it is critical for you to retrieve your data asap I can hack a version for this specific problem.
Otherwise let's think how to diagnose the problem and work out generic solution.

**Comment by dplagge** [comment] 2019-01-03 12:58
Thank you very much for looking into this!

I'm currently preparing our database for production. Then the backup should work. Luckily this was only the result of a test. :sweat_smile:  So it's not urgent to read to the data.

**Comment by x4m** [comment] 2019-01-03 15:49
Can you run [storage folder test](https://github.com/wal-g/wal-g/blob/master/test/s3_folder_test.go#L13) against your S3?
In order to do it you should remove Skip() call, put in your creds and run test.
This should be something like  ```make deps```, ```cd test``` and ```go test -run TestS3Folder```.

If the problem is easily reproducible through this test, I can change WAL-G so that it will pass tests on "regular" AWS and on your S3.

**Comment by x4m** [comment] 2019-07-31 08:39
As far as I remember, this was fixed in v0.2.9. Please reopen if reappear.

**Closed by x4m** 2019-07-31 08:39 UTC
