### ISSUE TITLE
wal-push failed, but exited with a 0 code?

### ISSUE THREAD

**Issue by diranged** [wal-g/wal-g#85] opened 2018-04-05 15:44 UTC
We got into a nasty situation yesterday when a `wal-g wal-push` failed, threw some log output (below), and then seems to have exited with a `0` code which allowed Postgres to clean up the failed WAL log.

Host Details:
 * Ubuntu 14.04
 * Postgres 9.6.6
 * WAL-G 0.1.7

```archive_command = 'envdir /etc/wal-g /usr/local/bin/wal-g wal-push %p'```

Log:
```
WAL PATH: us1/xxx/wal_005/000000020000D96A00000039.lz4
BUCKET: xxx.com
SERVER: us1/xxxx=
2018/04/04 20:54:21 upload: failed to upload 'pg_xlog/000000020000D96A0000003A': SerializationError: failed to decode S3 XML error response
	status code: 400, request id: 342A75FE7FA0F3D6, host id: 77+fUhrRM9zyLPA/OFYJxqEHOeryiTI4zwVzLOrz7U0LtU4eazY8uw+dLSo2gnocSAnj5Q3Dbng=
caused by: unexpected EOF. Restarting in 1.02 seconds
WAL PATH: us1/xxx/wal_005/000000020000D96A0000003A.lz4
BUCKET: xxx.com
SERVER: us1/xxx
```

Finally, here's a snapshot of the file as it was uploaded to S3 .. note, its 0 bytes:
```
$ aws s3 ls s3://xxx.com/us1/xxx/wal_005/000000020000D96A0000003A.lz4
2018-04-04 13:54:23          0 000000020000D96A0000003A.lz4
```

**Comment by x4m** [comment] 2018-04-05 17:06
@diranged , thanks for the report. Seems like a critical bug. I've stared at the code a bit, I definitely do not like the state of the upload() function and want to refactor it (). But do not see error handling bugs there. Will look at it in the morning again (UTC+5).

Maybe we should add some WAL-check functionality like 'check that all WALs from last backup are continuous and not zero-sized' and activate it by some flags during various commands like backup-list?

**Comment by diranged** [comment] 2018-04-05 18:30
I just think that the `wal-push` command should be _really sensitive_ to failures, and always err on the side of setting `exit_code: 1`. If it does this, Postgres will do the right thing and not move to the next file, and it will not mark the files for purging either.

**Comment by x4m** [comment] 2018-04-06 10:57
`always err on the side of setting exit_code`
This is absolutely correct invariant, all efforts are applied to honor it across code paths. But according to your report, this invariant is violated.
I'm still investigating where the possible bug may be.
Currently I see two possible vectors to eliminate or mitigate the bug:
1. Refactor upload code. There is homemade retry infrastructure which is not necessary since there is retry infrastructure in AWS SDK. This is the correct way. But it does not guaranty that things will be better - we replace the big old retry code with smaller new code. But new code may contain new bugs.
2. I can check after WAL-PUSH that file is actually there in S3 and has nonzero size. But this feels wrong. And it will slow down archiving. But this guarantees safety.
I need some time to think about it. If you do not insist I'll deal with this prior to #84, this issue is potential data loss and has priority №1.

**Comment by diranged** [comment] 2018-04-06 16:06
While I don't love the idea of uploading-and-then-checking-the-upload, there is an argument that it could be a parameter that you can turn on. Specifically, I actually think that it could check the MD5 of the source file, and compare it against the MD5 of the object in S3. This ensures that not only was the file uploaded, but that it was uploaded exactly as expected.

Thoughts?

**Comment by x4m** [comment] 2018-04-06 16:56
Yeah, MD5 is a good idea. I think that presence of this feature will make refactoring towards native AWS SDK retries safer. I'll do that. Optimistic ETA is around next Wednesday, will try to implement this ASAP.

**Comment by x4m** [comment] 2018-04-11 10:57
@diranged I've pushed a commit with --verify option of wal-push that will fail if S3 will report ETag different from MD5 digest of data we send.
There are few nitpicks.
1. AWS does not actually guaranty that ETag is MD5. https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html Though it is MD5 as long as file is smaller than 1 multipart size (20Mb) which holds for WAL
2. I really hate CLI code now. I cannot release this before refactoring argument parsing, which will take some more days.

Also, upload code is already refactored and hand-written retryer is replaced by Amazon AWS SDK retryer. This should ensure better code quality, but OTOH requires new QA before release.

Summary. I cant make you a binary with this feature ASAP or you can wait before proper pre-release.

**Comment by kaikuchn** [comment] 2018-06-19 16:15
> it is MD5 as long as file is smaller than 1 multipart size (20Mb) **which holds for WAL**

(emphasis mine)
Only usually, it is possible to change it when compiling Postgres. I don't know if anyone does that, but it is possible: https://www.postgresql.org/docs/9.6/static/runtime-config-preset.html

**Comment by x4m** [comment] 2018-06-19 17:09
@kaikuchn that's true, WAL file size is specified during configuration of PostgreSQL build. But that's not a big problem for a very optional feature.
This "verification" feature is somewhat paranoid, I think that S3 SDK upload should check MD5 itself. BTW it worth checking that.

**Comment by x4m** [comment] 2018-07-23 16:43
@qwertys-ru Thanks for the report!

It is definitely a bug, but it is a separate bug. Please file another issue, I've traced the root cause, will fix this tomorrow morning (UTC+5)

**Comment by qwertys-ru** [comment] 2018-07-23 18:10
@x4m thank you for quick response, new issue filed:

https://github.com/wal-g/wal-g/issues/102

**Comment by x4m** [comment] 2018-09-06 07:05
This issue seems to be resolved, I'll close it now. Please report if you will observe anything suspicious.

**Closed by x4m** 2018-09-06 07:05 UTC
