### ISSUE TITLE
wal-g failing on some wal files

### ISSUE THREAD

**Issue by nicholasklem** [wal-g/wal-g#333] opened 2019-07-16 08:02 UTC
I tried migrating from wal-e to wal-g in staging.

Every time I start up with wal-g as archive_command 1 file is not uploading:

postgresql.conf:
```
archive_command = 'envdir /etc/wal-g/env wal-g wal-push %p'
```
logs:
```
Jul 15 16:21:07 postgresql02-eu-w1d-01 postgresql[917]: [1172-1] db=,user= LOG:  archive command failed with exit code 1
Jul 15 16:21:07 postgresql02-eu-w1d-01 postgresql[917]: [1172-2] db=,user= DETAIL:  The failed archive command was: envdir /etc/wal-g/env wal-g wal-push pg_xlog/000000010000033D00000042
Jul 15 16:21:08 postgresql02-eu-w1d-01 postgresql[917]: [1173-1] db=,user= LOG:  archive command failed with exit code 1
Jul 15 16:21:08 postgresql02-eu-w1d-01 postgresql[917]: [1173-2] db=,user= DETAIL:  The failed archive command was: envdir /etc/wal-g/env wal-g wal-push pg_xlog/000000010000033D00000042
Jul 15 16:21:09 postgresql02-eu-w1d-01 postgresql[4011]: [22-1] db=[unknown],user=[unknown] LOG:  incomplete startup packet
Jul 15 16:21:09 postgresql02-eu-w1d-01 postgresql[917]: [1174-1] db=,user= LOG:  archive command failed with exit code 1
Jul 15 16:21:09 postgresql02-eu-w1d-01 postgresql[917]: [1174-2] db=,user= DETAIL:  The failed archive command was: envdir /etc/wal-g/env wal-g wal-push pg_xlog/000000010000033D00000042
Jul 15 16:21:09 postgresql02-eu-w1d-01 postgresql[917]: [1175-1] db=,user= WARNING:  archiving transaction log file "000000010000033D00000042" failed too many times, will try again later
```
WAL archives before and after this will upload fine. This specific file ...42 does not succeed even after 24 hours, this error message will just repeat.

A manual run of the command will succeed, but postgresql will still try to upload it.
```
Postgresql 9.6.1

$ wal-g --version
wal-g version v0.2.9	5bf0fcf	2019.04.22_06:20:02
```
Switching back to wal-e all files are synced fine.

Anything obvious I'm missing?

**Comment by x4m** [comment] 2019-07-16 18:51
Hi! Thanks for the report!

Can you please do the same thing with WALG_LOG_LEVEL=DEVEL?

**Comment by nicholasklem** [comment] 2019-07-17 09:28
Urk. After redirecting output to a logfile I got:
> exec: "getent": executable file not found in $PATH

Added /etc/wal-g/env/PATH:
/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

and it works!

Greetings
Nicholas

**Comment by x4m** [comment] 2019-07-17 15:28
Errr, sorry for this, we will fix that getent thing in next release.
It's known bug. We did not make prerelease with this and many other fixes due to unfinished features in master branch.

**Comment by x4m** [comment] 2019-07-17 15:29
I'll close this for now, if you will observe reproduction in next releases please reopen.

**Closed by x4m** 2019-07-17 15:29 UTC

**Comment by shlok007** [comment] 2019-11-08 08:47
Hey @x4m , can you please describe the issue a bit more? It seems like we are encountering the same and the above fix doesn't seem to work.

**Comment by x4m** [comment] 2019-11-08 12:07
@shlok007 there was a code to detect user home directory that used getent utility.
We removed this code in recent pre-releases.
