### ISSUE TITLE
backup-fetch fails with "Interpret: copy failed"

### ISSUE THREAD

**Issue by diranged** [wal-g/wal-g#84] opened 2018-04-05 15:36 UTC
Two servers failed to boot up and restore their databases last night. These two servers were booting in different AWS Regions, restoring from the same S3 backup. They both failed on exactly the same file, which indicates that we pushed a corrupt backup in some way.

The `backup-push` from the DB master had been run by hand, and there were no errors in the log output.

Master Server Details:
* Ubuntu 14.04
* Postgres 9.6.6
* WAL-G 0.1.7

DB Size: ~1.8TB

## Server 1 Failure
```
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: /base/16400/187655160
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: /base/16400/187655162
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: /base/16400/187655164
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: 2018/04/05 10:56:19 unexpected EOF
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: Interpret: copy failed
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: github.com/wal-g/wal-g.(*FileTarInterpreter).Interpret
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: 	/home/travis/gopath/src/github.com/wal-g/wal-g/tar.go:86
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: github.com/wal-g/wal-g.extractOne
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: 	/home/travis/gopath/src/github.com/wal-g/wal-g/extract.go:51
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: github.com/wal-g/wal-g.ExtractAll.func2.3
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: 	/home/travis/gopath/src/github.com/wal-g/wal-g/extract.go:156
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: runtime.goexit
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: 	/home/travis/.gimme/versions/go1.8.7.linux.amd64/src/runtime/asm_amd64.s:2197
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: extractOne: Interpret failed
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: github.com/wal-g/wal-g.extractOne
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: 	/home/travis/gopath/src/github.com/wal-g/wal-g/extract.go:53
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: github.com/wal-g/wal-g.ExtractAll.func2.3
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: 	/home/travis/gopath/src/github.com/wal-g/wal-g/extract.go:156
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: runtime.goexit
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: 	/home/travis/.gimme/versions/go1.8.7.linux.amd64/src/runtime/asm_amd64.s:2197
Info: Class[Wal_g::Db_restore]: Unscheduling all events on Class[Wal_g::Db_restore]
```

## Server 2 Failure
```
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: /base/16400/187655162
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: /base/16400/187655164
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: 2018/04/05 06:56:25 unexpected EOF
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: Interpret: copy failed
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: github.com/wal-g/wal-g.(*FileTarInterpreter).Interpret
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: 	/home/travis/gopath/src/github.com/wal-g/wal-g/tar.go:86
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: github.com/wal-g/wal-g.extractOne
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: 	/home/travis/gopath/src/github.com/wal-g/wal-g/extract.go:51
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: github.com/wal-g/wal-g.ExtractAll.func2.3
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: 	/home/travis/gopath/src/github.com/wal-g/wal-g/extract.go:156
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: runtime.goexit
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: 	/home/travis/.gimme/versions/go1.8.7.linux.amd64/src/runtime/asm_amd64.s:2197
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: extractOne: Interpret failed
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: github.com/wal-g/wal-g.extractOne
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: 	/home/travis/gopath/src/github.com/wal-g/wal-g/extract.go:53
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: github.com/wal-g/wal-g.ExtractAll.func2.3
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: 	/home/travis/gopath/src/github.com/wal-g/wal-g/extract.go:156
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: runtime.goexit
Notice: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: 	/home/travis/.gimme/versions/go1.8.7.linux.amd64/src/runtime/asm_amd64.s:2197
Info: Class[Wal_g::Db_restore]: Unscheduling all events on Class[Wal_g::Db_restore]
STDERR> Error: /Stage[main]/Wal_g::Db_restore/Exec[wal_g::db_restore]/returns: change from 'notrun' to ['0'] failed: '/usr/local/bin/wal-g-restore.sh' returned 1 instead of one of [0]
```

**Comment by x4m** [comment] 2018-04-05 16:49
Hi! Thanks for the report! Was it delta or full backup? Was it encrypted?

**Comment by diranged** [comment] 2018-04-05 18:25
@x4m, when you say `delta` or `full backup`, what do you mean? The command we ran was `wal-g backup-push /mnt/pgdata`. I am fairly sure those are full backups, right? It was not encrypted.

We have managed to pull down all of the `.lz4` files from the bad backup and are decoding them into `.tar` files now. I've already been able to untar the two files (999 & 1000) that seem to have `/base/16400/187655164` in them, and they seem fine. The file sizes look fine. In particular, the `187655164` file itself matches the source file on our DB master.

**Comment by diranged** [comment] 2018-04-05 18:29
Sorry I see the delta config now - no, we are not currently using that.

**Comment by diranged** [comment] 2018-04-05 23:02
@x4m, after a full day of testing, think this EOF failure is happening at the very end of the restore.. the actual tar/lz4 files are fine, so I think this is some other issue..

**Comment by diranged** [comment] 2018-04-06 00:43
@x4m just another update.. we've actually gotten a single machine to boot up, and we've had 9 others fail. THe DB Backup is being hosted in Oregon S3. The restores are happening in California and Virginia. The virginia restores have not yet worked. In California, we tried 3 machines, and the 3rd one was the charm.

It seems like it is intermittent .. but at the same time, _very_ reproducible.. but not 100%.

**Comment by x4m** [comment] 2018-04-06 05:49
@diranged I'm working on reproduction of your case but still unsuccessful. I've seen a similar fail with different stack
```
18:21:33 invalid lz4 data
DecompressLz4: lz4 write failed
github.com/x4m/wal-g.DecompressLz4
 /home/robot-gerrit/workspace/wal-g-build-deb/src/github.com/x4m/wal-g/obj-x86_64-linux-gnu/src/github.com/x4m/wal-g/decompress.go:141
github.com/x4m/wal-g.tarHandler
 /home/robot-gerrit/workspace/wal-g-build-deb/src/github.com/x4m/wal-g/obj-x86_64-linux-gnu/src/github.com/x4m/wal-g/extract.go:86
github.com/x4m/wal-g.ExtractAll.func2.2
 /home/robot-gerrit/workspace/wal-g-build-deb/src/github.com/x4m/wal-g/obj-x86_64-linux-gnu/src/github.com/x4m/wal-g/extract.go:148
runtime.goexit
 /usr/local/go/src/runtime/asm_amd64.s:2337
ExtractAll: lz4 decompress failed. Is archive encrypted?
github.com/x4m/wal-g.tarHandler
 /home/robot-gerrit/workspace/wal-g-build-deb/src/github.com/x4m/wal-g/obj-x86_64-linux-gnu/src/github.com/x4m/wal-g/extract.go:88
github.com/x4m/wal-g.ExtractAll.func2.2
 /home/robot-gerrit/workspace/wal-g-build-deb/src/github.com/x4m/wal-g/obj-x86_64-linux-gnu/src/github.com/x4m/wal-g/extract.go:148
runtime.goexit
 /usr/local/go/src/runtime/asm_amd64.s:2337
2018-04-02 18:21:33,362 [salt.loaded.int.module.cmdmod][ERROR   ][904] retcode: 1
```

Do you use AWS instance? Which flavour? If not do you use SSD or HDD, how big is RAM?

**Comment by diranged** [comment] 2018-04-06 15:53
@x4m, here are as many details as I can give you..

## SourceDB Master
* US-West-2 Oregon Region
* Postgres 9.6.6 on Ubuntu 14.04
* One logical database in the dump, extremely write-heavy database
* 7TB EBS-backed GP2 SSD Storage w/ ext4 fs
* R3.8XL Instance Type
* `4.4.0-111-generic #134~14.04.1-Ubuntu` kernel

## Streaming Slaves in local region
~6-7 live streaming slaves.. also all the same hardware/software config.

## Dump S3 Destination
* S3 Bucket in US-West-2 Oregon
* No encryption-on-upload
* No deltas
* Nightly Backups + WAL-Log-Shipping throughout the day

## S3/WAL-G Slaves in Remote Regions
We have a slave in California us-west-1 and in Virginia us-east-1. We made several changes in the process of trying to get things working. I'll try to document them here.

## Initial Hardware/OS/Software Config in US-West-1/US-East-1
Instance Type: i2.4xlarge
OS: Ubuntu 14.04 w/ Postgres 9.6.6 and WAL-G 0.1.7
Storage: Local SSD w/ EXT4 FS

This configuration failed in California 2 times in a row before we moved on to the next hardware configuration. In Virginia, this failed at least 4-5 times before we gave up.

## Migrated to I3.4xlarge Instances in US-West-1/US-East-1
We moved to I3's because we suspected something funky was happening with the I2's. In _California_ this worked, and we were able to get a DB up. In Virginia, we tried this hardware configuration (with a variety of software configs, see below) and had at least 7-8 failures and no successes. :(

## Software Tweak Attempts

* WAL-G 0.1.4
* WAL-G 0.1.6
* `MAX_CONCURRENT_DOWNLOADS=4`

**Comment by diranged** [comment] 2018-04-06 15:58
Re: Network bandwidth, etc... this configuration has been in place for the last 5+ years. Obviously over the years we continue to increase our server sizes (and database size). We used WAL-E until it became too slow to be reasonable (~6-9 hours to restore a server), and then we switched to WAL-G. When we switched to WAL-G, the DB was around ~1.4TB and at that point, the backup and restores worked fine.

I am doing a restoration test in US-West-2 - the region where the DB Backup Bucket resides - to see if that improves things or not. After that, I am going to try yet again to do a restoration in Virginia.

I have engaged AWS to see if there is any throttling or limiting happening on their end, but they say no. Also, we were able to use `aws s3 sync ...` to pull down the LZ4 files just fine from Amazon without any issues or errors.

Is there any way to get more logging output from WAL-G? Perhaps AWS Request ID Logs so that we can have Amazon correlate those with the requests on their end?

**Comment by x4m** [comment] 2018-04-06 16:50
I suspect a concurrency issue in data transformation libraries. Maybe in lz4 or tar. Earlier I was suspecting OpenGPG too because of our configurations.
If your case and mine are caused by the same bug, GPG is clear from suspicion and explains why we have different call stacks of failures.
The pipeline is S3->GPG->Lz4->Tar. I'll look into Lz4.

**Comment by x4m** [comment] 2018-04-06 17:02
There's only one "go", and it look safe https://github.com/pierrec/lz4/blob/master/reader.go#L188

**Comment by x4m** [comment] 2018-04-07 05:16
@diranged okaaay, then the real solution is to add retry to file download...

About IRC, @Scukerman was suggesting this, and I definiley want to create Slack channel for WAL-G. 
Here we go https://postgresteam.slack.com/messages/CA25P48P2/

**Comment by diranged** [comment] 2018-04-07 17:33
@x4m, unless you have a special email account, you cannot log into that slack service:

   ```If you have an @omniti.com, @wingspan.com, @getchef.com, @pgexperts.com, @citusdata.com, @8kdata.com, @peoplecall.com, @enterprisedb.com, @nabancard.com, @2ndquadrant.com (see 5 more)	email address, you can create an account.```

Unless there is a way for me to get an invite?

**Comment by x4m** [comment] 2018-04-07 17:46
@diranged here is invite app
https://postgres-slack.herokuapp.com/

**Comment by diranged** [comment] 2018-04-10 05:38
@x4m,
  I can't believe this .. but I think we tracked this down. After days and days of testing, we tried a new base Ubuntu image (`20180405`) with the latest version of the 4.4.0 kernel (`4.4.0-119-generic #143~14.04.1-Ubuntu SMP Mon Apr 2 18:04:36 UTC 2018`). _That solved it!_

  In the mean time we'd tried everything else.. including replicating the data to an S3 bucket in Virginia and restoring from that. Nothing worked. Everything failed reliably.

  I suspect that there is some strange kernel/ssd/etc issue going on here. The thing that got me going down this path was that we noticed our hosts would behave "funny" after the `wal-g` job failed. Until it failed, the hosts would run fine and the local storage was blazing (SSD) fast. After the failure, we would see the IO wait on the host go up (which makes no sense an SSD world), and there seemed to be some massive amount of disk reads happening (measured with `iostat`) even though no processes were running on the host.

**Comment by x4m** [comment] 2018-04-10 05:50
Um... that's strange. The error you have posted is about problems of reading (from net or lz4), not writing.

**Comment by chobostar** [comment] 2018-07-05 03:57
We got the same issue:

> unexpected EOF
Interpret: copy failed
github.com/wal-g/wal-g.(*FileTarInterpreter).Interpret
	/home/travis/gopath/src/github.com/wal-g/wal-g/tar.go:86
github.com/wal-g/wal-g.extractOne
	/home/travis/gopath/src/github.com/wal-g/wal-g/extract.go:51
github.com/wal-g/wal-g.ExtractAll.func2.3
	/home/travis/gopath/src/github.com/wal-g/wal-g/extract.go:156
runtime.goexit
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/runtime/asm_amd64.s:2361
extractOne: Interpret failed
github.com/wal-g/wal-g.extractOne
	/home/travis/gopath/src/github.com/wal-g/wal-g/extract.go:53
github.com/wal-g/wal-g.ExtractAll.func2.3
	/home/travis/gopath/src/github.com/wal-g/wal-g/extract.go:156
runtime.goexit
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/runtime/asm_amd64.s:2361

Given:
- WAL-G v0.1.10, also tried with v0.1.7
- Linux 4.16.9-1-ARCH x86_64
- PostgreSQL 10.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 7.3.0, 64-bit
- private S3 compatable storage
- ```MAX_CONCURRENT_DOWNLOADS```  from 2 to 4

(Also multiple tablespaces is used in master DB)

Error occurs each time on different stages after restoration 76-114GB of 467GB whole DB.

**Comment by x4m** [comment] 2018-07-05 14:57
Thanks for the report! I'm thinking of how to mitigate the problem. Stacks that you've send me in PM contained S3-implementation-specific errors. Can you tell more about it? can it throttle connections so that only one active download session is allowed? This would explain a lot...
One improvement that I can think of is automatically decreasing download concurrency if retries happen.

**Comment by WillPlatnick** [comment] 2018-07-31 23:46
We are running into the same issue on our side. WAL-G v0.1.10. We're not touching any environment variables that touch download concurrency.

For us, it's failing at the end of the restore. BUT, we're seeing something very weird about when it fails.

I've been hacking on a script where I used wal-e to do database restores and replacing it with wal-g. I had some issues where my backup-fetch was going to the wrong path, /var/lib/postgresql/main instead of /var/lib/postgresql/9.6/main.

I restored to the wrong path 3 times and ran into no issues on the wal-g side.

I tried to restore twice to the right path and it got all the way to the end, and then failed with this error. It fails in the exact same spot every time.

I then found this issue, did the restore again but intentionally to the wrong path, and it worked.

Could be a coincidence...but wanted to drop this experience in just in case.

I'm doing it again and I'll report in when it's done (it's a 1.2 TB backup so it'll take some time). I'll also do one with WALG_DOWNLOAD_CONCURRENCY set to 1 to see if that changes things.

**Comment by x4m** [comment] 2018-08-01 06:59
@WillPlatnick thanks for sharing. Looks like a coincidence, but I'll keep an eye on it. Still hope it's retry issue that will be fixed by https://github.com/wal-g/wal-g/commit/e7f3a6128b316cd8936a66d05bb3f2d0adcefeef

**Comment by WillPlatnick** [comment] 2018-08-14 14:30
FYI - We're still seeing this on v0.1.11 on every restore.

**Comment by WillPlatnick** [comment] 2018-08-14 15:26
It's also curious as to why it's ALWAYS happening around the end of the restore, without exception.

**Comment by x4m** [comment] 2018-08-14 15:49
That is not good.... Can I ask you to test fetch with diagnostic version of Wal-g? I'll compose one

**Comment by WillPlatnick** [comment] 2018-08-14 15:52
@x4m Yep.

**Comment by x4m** [comment] 2018-08-15 06:51
@WillPlatnick here's the patch. Please try restoration with it.
In this version, if we encounter tar download fails, we reattempt failed tars with concurrency 1.
here's compiled Linux binary https://yadi.sk/d/57XAT1PD3aEtcP

**Comment by WillPlatnick** [comment] 2018-08-21 21:52
@x4m I'm still working on getting this to finish. The restore is now taking much slower and I'm not exactly sure if it's because of my host, object store, or wal-g. I am running this without timeouts to try and get a full restore to happen.

**Comment by WillPlatnick** [comment] 2018-08-22 13:19
@x4m OK, it worked! The restore job took 7.5 hours. The same job takes several hours less with WAL-E, I'm assuming this might be related to concurrency?

**Comment by x4m** [comment] 2018-08-22 16:42
This "insistent retries" existed in two versions:
1. early one that I used to build the binary. This version uses concurrency 1 (sequential download)
2. later one with better logging and less drastic parallelism reduction which is referenced from the commit
The second one will be a bit faster.
But the actual time of backup fetching depends on a resource that is the bottleneck. If you are limited by ssd performance - WAL-E and WAL-G will be equivalent: you have to write same db to the disk. If you are limited by CPU - WAL-G will be significantly faster. And finally, if you are limited by network bandwidth - on default settings WAL-G will be 15% slower - it uses faster lz4 compression, which is faster in terms of CPU, but generates bigger archives (see #97 #99). If you choose lzma - you will get like 10x better compression but really big CPU consumption during backup-push. You can use Zstd compression which is a very good alternative (3x to lz4) with low CPU, I think eventually we will make Zstd default. But, right now, Zstd is not a good choice, you can see that no real release of WAL-G supports Zstd - on some very rare occasions I observe corrupted backups when I use Zstd, we will fix this, but right now it is a confirmed fact.

**Comment by x4m** [comment] 2018-08-22 17:43
@WillPlatnick I've pushed the feature to master. Thank you for testing!

**Comment by x4m** [comment] 2018-09-06 07:15
Seems like the issue is fixed. Please report any similar cases if you observe one.

**Closed by x4m** 2018-09-06 07:15 UTC

**Comment by evansd** [comment] 2018-11-17 20:14
Hi, I've been having exactly this issue with restores using both v0.1.15 and v0.2.0 of WAL-G. But using the version linked [above](https://github.com/wal-g/wal-g/issues/84#issuecomment-413110102) works perfectly.

I wonder if it would be possible to have a config option to run WAL-G in some sort of "slow but reliable" mode when doing restores? I appreciate all the work that's going in to making WAL-G so fast. But for something like a backup tool you really don't want to be faced with a situation where you can't restore because of this kind of hard-to-debug intermittent failure. So it would be nice to know there was always on option to run WAL-G in "basic" mode and recover your data.

**Comment by koehn** [comment] 2019-02-20 18:13
FWIW I'm experiencing the same thing with v0.2.5. If I set `WALG_DOWNLOAD_CONCURRENCY=1` things work fine (albeit slowly). Without restricting concurrency I get either, `DecryptAndDecompressTar: lz4 decompress failed. Is archive encrypted?: DecompressLz4: lz4 write failed: unexpected EOF` or `Extraction error in part_004.tar.lz4: extractOne: Interpret failed: Interpret: copy failed: unexpected EOF` or both. 

You can test out my Docker image at `koehn/postgres-wal-g:11.1-v2.5.0-0`. It just extends the `postgres:11.1` image by adding wal-g and a few support scripts in the `/wal-g` directory. I'm using DigitalOcean Spaces for my S3 implementation.
