### ISSUE TITLE
Decompress and decrypt bug in 0.1.14

### ISSUE THREAD

**Issue by martinisoft** [wal-g/wal-g#130] opened 2018-11-14 19:57 UTC
During the base backup fetch phase we hit a series of errors with the decompression and decryption portion. Here is the error we get during the backup fetch:

```
2018/11/14 18:39:07 DecryptAndDecompressTar: lz4 decompress failed. Is archive encrypted?: DecompressLz4: lz4 write failed: lz4: invalid source or destination buffer too short
```

We backup using 0.1.10 right now and trying 0.1.12 for restoring works consistently. Upgrading to 0.1.14 for restores causes this error to come up consistently so I am not sure which change between 0.1.12 and 0.1.14 caused this.

**Comment by x4m** [comment] 2018-11-15 05:48
Hi @martinisoft !
Thanks for reporting!
I've found two critical issues:
1. I've thoroughly tested in QA env branch REL0_1_STABLE. And somehow used master for tag v0.1.4 instead of REL0_1_STABLE. I'll fix that ASAP.
2. In fact, you've been using v0.2.0 - this is pre-release, seems like a problem was introduced by updating lz4 library. I cannot reproduce this problem in my env and will be happy if you could help me by testing v0.2.0. I'll make a version with old lz4, that version was serving us more than a year without issues. Also, we could try to identify the problem and report it to lz4 maintainers.

**Comment by x4m** [comment] 2018-11-15 05:58
1. I've re-issued v0.1.14 with tag v0.1.15. Now it should be safe.
2. About lz4. We were using https://github.com/pierrec/lz4/commit/5a3d2245f97fc249850e7802e3c01fad02a1c316 for a long time. WAL-G v0.2.0 now uses https://github.com/pierrec/lz4/commit/1958fd8fff7f115e79725b1288e0b878b3e06b00 which contains known bug https://github.com/pierrec/lz4/issues/29#issuecomment-416052849 (I cannot conclude whether it is related or not). Should we downgrade to known good version or upgrade to the latest release of lz4? @martinisoft How do you think?

**Comment by x4m** [comment] 2018-12-16 17:15
If there are no more questions, let's close this for now. If you have some questions feel free to create new or reopen this issue. Thanks!

**Closed by x4m** 2018-12-16 17:15 UTC
