### ISSUE TITLE
wal-g delete before FIND_FULL panic

### ISSUE THREAD

**Issue by Aytuar** [wal-g/wal-g#925] opened 2021-04-07 08:50 UTC
wal-g version v0.2.19   `8dba4f4` 2020.11.30_09:18:01

We have an empty list of backups, haven't done a single one yet
```
bash-4.2$ wal-g backup-list
INFO: 2021/04/07 11:36:59.388493 No backups found
```

Execute the `delete before FIND_FULL`  command. For example, we have it in the schedule and the date is calculated.
```
-bash-4.2$ wal-g delete before FIND_FULL 2021-03-13T21:02:09Z
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x17c43bc]

goroutine 1 [running]:
github.com/wal-g/wal-g/internal.FindTargetBeforeTime(0x1fe86a0, 0xc000231730, 0x0, 0xed7df1f51, 0x0, 0x2, 0xc0001da320, 0x1cce7c8, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/delete_handler.go:144 +0x10c
github.com/wal-g/wal-g/internal.HandleDeleteBefore(0x1fe86a0, 0xc000231730, 0xc0002efdc0, 0x2, 0x2, 0x1c7cf00, 0xc0001da320, 0x1cce7c8)
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/delete_handler.go:405 +0x43a
github.com/wal-g/wal-g/cmd/pg.runDeleteBefore(0x2badb40, 0xc0002efdc0, 0x2, 0x2)
        /home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/delete.go:55 +0xea
github.com/spf13/cobra.(*Command).execute(0x2badb40, 0xc0002efd00, 0x2, 0x2, 0x2badb40, 0xc0002efd00)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x2bab840, 0xac366a, 0x2bc1000, 0xc000000180)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:864
github.com/wal-g/wal-g/cmd/pg.Execute()
        /home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/pg.go:39 +0x31
main.main()
        /home/travis/gopath/src/github.com/wal-g/wal-g/main/pg/main.go:8 +0x20
```

The `delete everything` command works without errors.
```
-bash-4.2$ wal-g delete everything
INFO: 2021/04/07 11:38:35.690216 retrieving permanent objects
INFO: 2021/04/07 11:38:35.900890 Objects in folder:
```

**Comment by usernamedt** [comment] 2021-04-09 12:39
Looks like it may have been fixed in https://github.com/wal-g/wal-g/pull/818

Does this error reproduce on master branch?

**Comment by Aytuar** [comment] 2021-04-09 13:06
Yes.

**Comment by usernamedt** [comment] 2021-04-09 13:48
Doesn't reproduce
```
usernamedt-osx:wal-g usernamedt$ wal-g delete before FIND_FULL 2021-03-13T21:02:09Z --config /Users/usernamedt/wal-g.yaml 
INFO: 2021/04/09 18:47:49.052444 retrieving permanent objects
INFO: 2021/04/09 18:47:49.423118 No backup found for deletion
```

**Closed** 2021-04-09 13:50 UTC

**Comment by Aytuar** [comment] 2021-04-09 14:14
Yes, right, it works from the current commit. When I tested from the master branch it crashed. But I didn't write down what the last commit was. (
