### ISSUE TITLE
Missing files in backup-fetch of wal-e archive

### ISSUE THREAD

**Issue by cjhubert** [wal-g/wal-g#172] opened 2019-01-25 21:24 UTC
# Details

- wal-g Version = `v0.2.4`
- wal-e Version = `v1.1.0`
- Postgres Version = `10`

Attempting to `backup-fetch` a backup made with `wal-e` using `wal-g`. I was getting
the pg control issue prior, but moving to `v0.2.4` fixed that. Now, however,
I'm getting this odd issue where all files in the root directory are missing.
Files inside directories appear to be present, however.

I can restore this `wal-e` backup with `wal-e`. And as an aside, doing a
`backup-fetch` of a completely separate `wal-g` backup with `wal-g` has no
isses (no missing files). I appear to be unable to restore a `wal-e` backup with `wal-g`.

# Logs

Running `wal-e backup-fetch`:

```sh
$ AWS_ACCESS_KEY_ID=<redacted> \
AWS_SECRET_ACCESS_KEY=<redacted> \
WALE_S3_PREFIX=s3://bucket/db \
wal-e backup-fetch /walefetch LATEST

wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-fetch".
        STRUCTURED: time=2019-01-25T20:05:55.978052-00 pid=22346
wal_e.worker.s3.s3_worker INFO     MSG: beginning partition download
        DETAIL: The partition being downloaded is part_00000000.tar.lzo.
        HINT: The absolute S3 key is db/basebackups_005/base_000000010000051100000089_00000040/tar_partitions/part_00000000.tar.lzo.
        STRUCTURED: time=2019-01-25T20:05:56.645186-00 pid=22346
```

```sh
$ ls -al /walefetch
drwx------. 19 postgres postgres 4096 Jan 25 20:06 .
drwxr-xr-x.  1 root     root     4096 Jan 25 20:05 ..
-rwx------.  1 postgres postgres    3 Jan  9 21:41 PG_VERSION
-rw-------.  1 postgres postgres  239 Jan 25 18:45 backup_label
drwx------.  6 postgres postgres 4096 Jan 25 20:05 base
drwx------.  2 postgres postgres 4096 Jan 25 20:05 global
drwx------.  2 postgres postgres 4096 Jan  9 21:41 pg_commit_ts
drwx------.  2 postgres postgres 4096 Jan  9 21:41 pg_dynshmem
drwx------.  4 postgres postgres 4096 Jan 25 20:06 pg_logical
drwx------.  4 postgres postgres 4096 Jan 25 20:05 pg_multixact
drwx------.  2 postgres postgres 4096 Jan 25 20:05 pg_notify
drwx------.  2 postgres postgres 4096 Jan  9 21:41 pg_replslot
drwx------.  2 postgres postgres 4096 Jan  9 21:41 pg_serial
drwx------.  2 postgres postgres 4096 Jan  9 21:41 pg_snapshots
drwx------.  2 postgres postgres 4096 Jan 11 20:09 pg_stat
drwx------.  2 postgres postgres 4096 Jan  9 21:41 pg_stat_tmp
drwx------.  2 postgres postgres 4096 Jan 25 20:05 pg_subtrans
drwx------.  2 postgres postgres 4096 Jan  9 21:41 pg_tblspc
drwx------.  2 postgres postgres 4096 Jan  9 21:41 pg_twophase
drwx------.  2 postgres postgres 4096 Jan 25 18:45 pg_wal
drwx------.  2 postgres postgres 4096 Jan 25 20:06 pg_xact
-rw-------.  1 postgres postgres  119 Jan 11 20:27 postgresql.auto.conf
-rwx------.  1 postgres postgres  161 Jan 11 20:09 postgresql_autogen.conf
-rwx------.  1 postgres postgres  127 Jan 11 20:09 postgresql_user.conf
```

Running `wal-g backup-fetch` on the same bucket:

```sh
$ AWS_ACCESS_KEY_ID=<redacted> \
AWS_SECRET_ACCESS_KEY=<redacted> \
WALG_S3_PREFIX=s3://bucket/db \
wal-g backup-fetch /walgfetch LATEST

Path:  db/
INFO: 2019/01/25 20:19:46.826069 LATEST backup is: 'base_000000010000051100000089_00000040'
INFO: 2019/01/25 20:19:47.359668 Finished decompression of part_00000000.tar.lzo
INFO: 2019/01/25 20:19:47.359843 Finished extraction of part_00000000.tar.lzo
INFO: 2019/01/25 20:19:47.359921 
Backup extraction complete.
```

```sh
$ ls -al /walgfetch
drwx------. 19 root root 4096 Jan 25 20:05 .
drwxr-xr-x.  1 root root 4096 Jan 25 20:05 ..
-rw-------.  1 root root  239 Jan 25 20:05 backup_label
drwx------.  6 root root 4096 Jan 25 20:05 base
drwx------.  2 root root 4096 Jan 25 20:05 global
drwx------.  2 root root 4096 Jan 25 20:05 pg_commit_ts
drwx------.  2 root root 4096 Jan 25 20:05 pg_dynshmem
drwx------.  4 root root 4096 Jan 25 20:05 pg_logical
drwx------.  4 root root 4096 Jan 25 20:05 pg_multixact
drwx------.  2 root root 4096 Jan 25 20:05 pg_notify
drwx------.  2 root root 4096 Jan 25 20:05 pg_replslot
drwx------.  2 root root 4096 Jan 25 20:05 pg_serial
drwx------.  2 root root 4096 Jan 25 20:05 pg_snapshots
drwx------.  2 root root 4096 Jan 25 20:05 pg_stat
drwx------.  2 root root 4096 Jan 25 20:05 pg_stat_tmp
drwx------.  2 root root 4096 Jan 25 20:05 pg_subtrans
drwx------.  2 root root 4096 Jan 25 20:05 pg_tblspc
drwx------.  2 root root 4096 Jan 25 20:05 pg_twophase
drwx------.  2 root root 4096 Jan 25 20:05 pg_wal
drwx------.  2 root root 4096 Jan 25 20:05 pg_xact
```

There's also the user/group permission difference, but I can definitely say that
postgres is unhappy about missing files:

```sh
2019-01-25 17:02:09.783 GMT [25] LOG:  skipping missing configuration file "/walgfetch/postgresql.auto.conf"
2019-01-25 17:02:09 UTC [25-2] FATAL:  "/walgfetch" is not a valid data directory
2019-01-25 17:02:09 UTC [25-3] DETAIL:  File "/walgfetch/PG_VERSION" is missing.
```

**Comment by cjhubert** [comment] 2019-01-29 21:21
Sorry for the slow reply. Similar to the other issue linked, I haven't been able to think of a way to make a backup that would be safe to share out. Kind of wish wal-e had some example base backups but didn't see anything looking through their repo.

I can say that I can simply download the `.tar.lzo` file, run `lzop -d <filename>`, then `tar -xvf <lzop decompressed filename>` and see the entire directory, root files and all. I've been looking through the code here but so far haven't had any luck figuring out what's going on

**Comment by cjhubert** [comment] 2019-01-30 22:17
I was able to push a back up with wal-e with the postgres docker image and replicate this issue. I'll attempt to attach the files wal-e pushed. Note that this is an empty database, but the same issue persists (wal-e shows the files, wal-g does not). If there's any other information I can provide, please let me know 😄 

[basebackups_005.zip](https://github.com/wal-g/wal-g/files/2814720/basebackups_005.zip)

**Comment by x4m** [comment] 2019-02-03 11:32
Thanks! I've finally tracked it down.
Function GetRestoredBackupFilesToUnwrap() is not working correctly for WAL-E, because it is using WAL-G format.
@Tinsane , I propose using nil field of FilesToUnwrap as a marker "Extract everything". Actually, current code also breaks backups of pre-0.1.3 backups too, because of 0.1.3 introduced sentinel internals, before this it was empty :)

**Comment by x4m** [comment] 2019-02-03 11:35
Also, I suspect some of this FilesToUnwrap code is responsible for #177 too. There are files missing in multilevel deltas, I could not reproduce that still, but think we can just stare at the code closely and compel the bug to go out to give up.

**Comment by x4m** [comment] 2019-02-20 12:58
Please test that issue is fixed in the recent version. Now we have integration tests, so we will detect this early. If something is still broken plz reopen.

**Comment by x4m** [comment] 2019-02-20 13:04
We still have the problem with correct permimssions of backup, I think we should do as pg_basebackup does. If you do not mind may I ask you to close this issue and open one about file access right?

**Closed by x4m** 2019-02-20 13:04 UTC
