### ISSUE TITLE
Purging all WALS durig delete operation  version 0.2.4

### ISSUE THREAD

**Issue by kel00s** [wal-g/wal-g#230] opened 2019-04-02 18:03 UTC
Hi all,

We started using wal-g for doing backup and restoring postgres into GCP. During the first step it removing all wal files within bucket. Below is my simple script.

```
#!/bin/bash
export PG_DATA_DIR="/var/lib/pgsql/9.6/data"
export WAL_G=`which wal-g`
export RETAIN_BACKUPS=2
export PGHOST="/var/run/postgresql"
export PGUSER="postgres"

envdir /etc/wal-e.d/env ${WAL_G} delete retain FULL ${RETAIN_BACKUPS} --confirm > /tmp/wal-g-backup.log 2>&1

if [ $? -ne 0 ] ;
then
  echo "old backups, wals not purged"
else
  echo "old backups, wals are purged"
fi

envdir /etc/wal-e.d/env ${WAL_G} backup-push ${PG_DATA_DIR} > /tmp/wal-g-backup.log 2>&1

if [ $? -ne 0 ] ;
then
  echo "backup push failed"
```

**Comment by kel00s** [comment] 2019-04-02 18:17
Update: I verified the same with v0.2.7

**Comment by x4m** [comment] 2019-04-03 05:23
@g0djan as long as you are refactoring deletes now, can you please look into this? seems quite critical..

**Comment by x4m** [comment] 2019-04-03 08:06
I do not observe this behaviour on our installation.
Can you plz try this with WALG_LOG_LEVEL=DEVEL and provide output?

**Comment by CyberDem0n** [comment] 2019-04-03 09:13
I also can't reproduce removal of all WALs from backup, but it looks like I've found another issue with 0.2.7:
```
./wal-g backup-list
Path:  some/path/
name                                   last_modified        wal_segment_backup_start
base_00000022000000020000004B_00000040 2019-03-30T01:00:16Z 00000022000000020000004B_00000040
base_00000022000000020000004D_00000040 2019-04-01T01:00:17Z 00000022000000020000004D_00000040
base_000000240000000200000058_00000040 2019-04-02T01:00:15Z 000000240000000200000058_00000040
base_000000240000000200000061_00000040 2019-04-03T01:00:13Z 000000240000000200000061_00000040
```

```
./wal-g delete before base_00000022000000020000004D_00000040 --confirm
Path:  some/path/
INFO: 2019/04/03 08:54:21.789278 base_000000240000000200000061_00000040 skipped
INFO: 2019/04/03 08:54:21.789315 base_000000240000000200000058_00000040 skipped
INFO: 2019/04/03 08:54:21.789319 base_00000022000000020000004D_00000040 skipped
INFO: 2019/04/03 08:54:21.789323 base_00000022000000020000004B_00000040 will be deleted
INFO: 2019/04/03 08:54:21.808388 000000010000000000000024.partial.lzo
INFO: 2019/04/03 08:54:21.808411 delete 000000010000000000000024.partial.lzo
INFO: 2019/04/03 08:54:21.808415 00000002.history.lzo
INFO: 2019/04/03 08:54:21.808425 delete 00000002.history.lzo
INFO: 2019/04/03 08:54:21.808437 00000002000000000000002F.partial.lzo
INFO: 2019/04/03 08:54:21.808449 delete 00000002000000000000002F.partial.lzo
INFO: 2019/04/03 08:54:21.808459 00000003.history.lzo
INFO: 2019/04/03 08:54:21.808470 delete 00000003.history.lzo
INFO: 2019/04/03 08:54:21.808473 00000003000000000000003C.partial.lzo
INFO: 2019/04/03 08:54:21.808481 delete 00000003000000000000003C.partial.lzo
INFO: 2019/04/03 08:54:21.808484 00000004.history.lzo
INFO: 2019/04/03 08:54:21.808499 delete 00000004.history.lzo
INFO: 2019/04/03 08:54:21.808508 00000004000000000000003D.partial.lzo
INFO: 2019/04/03 08:54:21.808513 delete 00000004000000000000003D.partial.lzo
INFO: 2019/04/03 08:54:21.808525 00000005.history.lzo
INFO: 2019/04/03 08:54:21.808530 delete 00000005.history.lzo
INFO: 2019/04/03 08:54:21.808542 00000005000000000000003E.partial.lzo
INFO: 2019/04/03 08:54:21.808553 delete 00000005000000000000003E.partial.lzo
INFO: 2019/04/03 08:54:21.808559 00000006.history.lzo
INFO: 2019/04/03 08:54:21.808570 delete 00000006.history.lzo
INFO: 2019/04/03 08:54:21.808580 00000006000000000000007B.partial.lzo
INFO: 2019/04/03 08:54:21.808589 delete 00000006000000000000007B.partial.lzo
INFO: 2019/04/03 08:54:21.808599 00000007.history.lzo
INFO: 2019/04/03 08:54:21.808604 delete 00000007.history.lzo
INFO: 2019/04/03 08:54:21.808609 00000007000000000000007D.partial.lzo
INFO: 2019/04/03 08:54:21.808613 delete 00000007000000000000007D.partial.lzo
INFO: 2019/04/03 08:54:21.808617 00000008.history.lzo
INFO: 2019/04/03 08:54:21.808621 delete 00000008.history.lzo
INFO: 2019/04/03 08:54:21.808627 000000080000000000000084.partial.lzo
INFO: 2019/04/03 08:54:21.808631 delete 000000080000000000000084.partial.lzo
INFO: 2019/04/03 08:54:21.808637 00000009.history.lzo
INFO: 2019/04/03 08:54:21.808641 delete 00000009.history.lzo
INFO: 2019/04/03 08:54:21.808647 0000000900000000000000AA.partial.lzo
INFO: 2019/04/03 08:54:21.808651 delete 0000000900000000000000AA.partial.lzo
INFO: 2019/04/03 08:54:21.808658 0000000A.history.lzo
INFO: 2019/04/03 08:54:21.808663 delete 0000000A.history.lzo
INFO: 2019/04/03 08:54:21.808675 0000000A00000000000000AC.partial.lzo
INFO: 2019/04/03 08:54:21.808682 delete 0000000A00000000000000AC.partial.lzo
INFO: 2019/04/03 08:54:21.808692 0000000B.history.lzo
INFO: 2019/04/03 08:54:21.808697 delete 0000000B.history.lzo
INFO: 2019/04/03 08:54:21.808712 0000000B00000000000000AF.partial.lzo
INFO: 2019/04/03 08:54:21.808717 delete 0000000B00000000000000AF.partial.lzo
INFO: 2019/04/03 08:54:21.808722 0000000C.history.lzo
INFO: 2019/04/03 08:54:21.808734 delete 0000000C.history.lzo
INFO: 2019/04/03 08:54:21.808745 0000000C00000000000000BC.partial.lzo
INFO: 2019/04/03 08:54:21.808759 delete 0000000C00000000000000BC.partial.lzo
INFO: 2019/04/03 08:54:21.808764 0000000D.history.lzo
INFO: 2019/04/03 08:54:21.808769 delete 0000000D.history.lzo
INFO: 2019/04/03 08:54:21.808780 0000000D00000000000000F4.partial.lzo
INFO: 2019/04/03 08:54:21.808784 delete 0000000D00000000000000F4.partial.lzo
INFO: 2019/04/03 08:54:21.808789 0000000E.history.lzo
INFO: 2019/04/03 08:54:21.808802 delete 0000000E.history.lzo
INFO: 2019/04/03 08:54:21.808806 0000000E0000000100000012.partial.lzo
INFO: 2019/04/03 08:54:21.808811 delete 0000000E0000000100000012.partial.lzo
INFO: 2019/04/03 08:54:21.808822 0000000F.history.lzo
INFO: 2019/04/03 08:54:21.808835 delete 0000000F.history.lzo
INFO: 2019/04/03 08:54:21.808851 0000000F0000000100000022.partial.lzo
INFO: 2019/04/03 08:54:21.808864 delete 0000000F0000000100000022.partial.lzo
INFO: 2019/04/03 08:54:21.808869 00000010.history.lzo
INFO: 2019/04/03 08:54:21.808873 delete 00000010.history.lzo
INFO: 2019/04/03 08:54:21.808877 000000100000000100000035.partial.lzo
INFO: 2019/04/03 08:54:21.808882 delete 000000100000000100000035.partial.lzo
INFO: 2019/04/03 08:54:21.808894 00000011.history.lzo
INFO: 2019/04/03 08:54:21.808898 delete 00000011.history.lzo
INFO: 2019/04/03 08:54:21.808905 000000110000000100000036.partial.lzo
INFO: 2019/04/03 08:54:21.808910 delete 000000110000000100000036.partial.lzo
INFO: 2019/04/03 08:54:21.808924 00000012.history.lzo
INFO: 2019/04/03 08:54:21.808936 delete 00000012.history.lzo
INFO: 2019/04/03 08:54:21.808949 000000120000000100000038.partial.lzo
INFO: 2019/04/03 08:54:21.808954 delete 000000120000000100000038.partial.lzo
INFO: 2019/04/03 08:54:21.808957 00000013.history.lzo
INFO: 2019/04/03 08:54:21.808970 delete 00000013.history.lzo
INFO: 2019/04/03 08:54:21.808973 000000130000000100000042.partial.lzo
INFO: 2019/04/03 08:54:21.808977 delete 000000130000000100000042.partial.lzo
INFO: 2019/04/03 08:54:21.808987 00000014.history.lzo
INFO: 2019/04/03 08:54:21.808991 delete 00000014.history.lzo
INFO: 2019/04/03 08:54:21.809004 000000140000000100000048.partial.lzo
INFO: 2019/04/03 08:54:21.809009 delete 000000140000000100000048.partial.lzo
INFO: 2019/04/03 08:54:21.809020 00000015.history.lzo
INFO: 2019/04/03 08:54:21.809033 delete 00000015.history.lzo
INFO: 2019/04/03 08:54:21.809045 000000150000000100000049.partial.lzo
INFO: 2019/04/03 08:54:21.809049 delete 000000150000000100000049.partial.lzo
INFO: 2019/04/03 08:54:21.809061 00000016.history.lzo
INFO: 2019/04/03 08:54:21.809072 delete 00000016.history.lzo
INFO: 2019/04/03 08:54:21.809082 00000016000000010000004C.partial.lzo
INFO: 2019/04/03 08:54:21.809093 delete 00000016000000010000004C.partial.lzo
INFO: 2019/04/03 08:54:21.809105 00000017.history.lzo
INFO: 2019/04/03 08:54:21.809114 delete 00000017.history.lzo
INFO: 2019/04/03 08:54:21.809125 000000170000000100000092.partial.lzo
INFO: 2019/04/03 08:54:21.809135 delete 000000170000000100000092.partial.lzo
INFO: 2019/04/03 08:54:21.809145 00000018.history.lzo
INFO: 2019/04/03 08:54:21.809160 delete 00000018.history.lzo
INFO: 2019/04/03 08:54:21.809164 000000180000000100000095.partial.lzo
INFO: 2019/04/03 08:54:21.809175 delete 000000180000000100000095.partial.lzo
INFO: 2019/04/03 08:54:21.809179 00000019.history.lzo
INFO: 2019/04/03 08:54:21.809189 delete 00000019.history.lzo
INFO: 2019/04/03 08:54:21.809194 00000019000000010000009E.partial.lzo
INFO: 2019/04/03 08:54:21.809199 delete 00000019000000010000009E.partial.lzo
INFO: 2019/04/03 08:54:21.809209 0000001A.history.lzo
INFO: 2019/04/03 08:54:21.809213 delete 0000001A.history.lzo
INFO: 2019/04/03 08:54:21.809220 0000001A00000001000000A0.partial.lzo
INFO: 2019/04/03 08:54:21.809225 delete 0000001A00000001000000A0.partial.lzo
INFO: 2019/04/03 08:54:21.809237 0000001B.history.lzo
INFO: 2019/04/03 08:54:21.809241 delete 0000001B.history.lzo
INFO: 2019/04/03 08:54:21.809246 0000001B00000001000000AD.partial.lzo
INFO: 2019/04/03 08:54:21.809280 delete 0000001B00000001000000AD.partial.lzo
INFO: 2019/04/03 08:54:21.809288 0000001C.history.lzo
INFO: 2019/04/03 08:54:21.809292 delete 0000001C.history.lzo
INFO: 2019/04/03 08:54:21.809308 0000001C00000001000000C4.partial.lzo
INFO: 2019/04/03 08:54:21.809313 delete 0000001C00000001000000C4.partial.lzo
INFO: 2019/04/03 08:54:21.809318 0000001D.history.lzo
INFO: 2019/04/03 08:54:21.809329 delete 0000001D.history.lzo
INFO: 2019/04/03 08:54:21.809342 0000001D00000001000000D7.partial.lzo
INFO: 2019/04/03 08:54:21.809355 delete 0000001D00000001000000D7.partial.lzo
INFO: 2019/04/03 08:54:21.809366 0000001E.history.lzo
INFO: 2019/04/03 08:54:21.809377 delete 0000001E.history.lzo
INFO: 2019/04/03 08:54:21.809382 0000001F.history.lzo
INFO: 2019/04/03 08:54:21.809392 delete 0000001F.history.lzo
INFO: 2019/04/03 08:54:21.809397 0000001F00000001000000FA.partial.lzo
INFO: 2019/04/03 08:54:21.809408 delete 0000001F00000001000000FA.partial.lzo
INFO: 2019/04/03 08:54:21.809421 00000020.history.lzo
INFO: 2019/04/03 08:54:21.809433 delete 00000020.history.lzo
INFO: 2019/04/03 08:54:21.809446 00000020000000020000002D.partial.lzo
INFO: 2019/04/03 08:54:21.809450 delete 00000020000000020000002D.partial.lzo
INFO: 2019/04/03 08:54:21.809459 00000021.history.lzo
INFO: 2019/04/03 08:54:21.809467 delete 00000021.history.lzo
INFO: 2019/04/03 08:54:21.809481 000000210000000200000032.partial.lzo
INFO: 2019/04/03 08:54:21.809486 delete 000000210000000200000032.partial.lzo
INFO: 2019/04/03 08:54:21.809499 00000022.history.lzo
INFO: 2019/04/03 08:54:21.809509 delete 00000022.history.lzo
INFO: 2019/04/03 08:54:21.809518 00000022000000020000004B.00000028.backup.lzo
INFO: 2019/04/03 08:54:21.809525 delete 00000022000000020000004B.00000028.backup.lzo
INFO: 2019/04/03 08:54:21.809535 00000022000000020000004B.lzo
INFO: 2019/04/03 08:54:21.809546 delete 00000022000000020000004B.lzo
INFO: 2019/04/03 08:54:21.809551 00000022000000020000004C.lzo
INFO: 2019/04/03 08:54:21.809555 delete 00000022000000020000004C.lzo
INFO: 2019/04/03 08:54:21.809560 00000022000000020000004D.00000028.backup.lzo
INFO: 2019/04/03 08:54:21.809572 delete 00000022000000020000004D.00000028.backup.lzo
INFO: 2019/04/03 08:54:21.809576 00000022000000020000004D.lzo
INFO: 2019/04/03 08:54:21.809587 delete 00000022000000020000004D.lzo
INFO: 2019/04/03 08:54:21.809591 00000022000000020000004E.lzo
INFO: 2019/04/03 08:54:21.809601 00000022000000020000004F.partial.lzo
INFO: 2019/04/03 08:54:21.809609 00000023.history.lzo
INFO: 2019/04/03 08:54:21.809620 00000023000000020000004F.lzo
INFO: 2019/04/03 08:54:21.809633 000000230000000200000050.lzo
INFO: 2019/04/03 08:54:21.809638 000000230000000200000051.lzo
INFO: 2019/04/03 08:54:21.809642 000000230000000200000052.00000028.backup.lzo
INFO: 2019/04/03 08:54:21.809647 000000230000000200000052.lzo
INFO: 2019/04/03 08:54:21.809662 000000230000000200000053.lzo
INFO: 2019/04/03 08:54:21.809666 000000230000000200000054.lzo
INFO: 2019/04/03 08:54:21.809684 000000230000000200000055.lzo
INFO: 2019/04/03 08:54:21.809689 000000230000000200000056.partial.lzo
INFO: 2019/04/03 08:54:21.809700 00000024.history.lzo
INFO: 2019/04/03 08:54:21.809709 000000240000000200000056.lzo
INFO: 2019/04/03 08:54:21.809719 000000240000000200000057.lzo
INFO: 2019/04/03 08:54:21.809724 000000240000000200000058.00000028.backup.lzo
INFO: 2019/04/03 08:54:21.809728 000000240000000200000058.lzo
INFO: 2019/04/03 08:54:21.809740 000000240000000200000059.lzo
INFO: 2019/04/03 08:54:21.809753 00000024000000020000005A.lzo
INFO: 2019/04/03 08:54:21.809758 00000024000000020000005B.lzo
INFO: 2019/04/03 08:54:21.809764 00000024000000020000005C.lzo
INFO: 2019/04/03 08:54:21.809773 00000024000000020000005D.lzo
INFO: 2019/04/03 08:54:21.809781 00000024000000020000005E.lzo
INFO: 2019/04/03 08:54:21.809792 00000024000000020000005F.lzo
INFO: 2019/04/03 08:54:21.809797 000000240000000200000060.lzo
INFO: 2019/04/03 08:54:21.809806 000000240000000200000061.00000028.backup.lzo
INFO: 2019/04/03 08:54:21.809819 000000240000000200000061.lzo
```

`00000022000000020000004D` is required for `base_00000022000000020000004D_00000040` but it was deleted, therefore `base_00000022000000020000004D_00000040` become useless :(

**Comment by CyberDem0n** [comment] 2019-04-03 09:20
And one more addition:
`base_00000022000000020000004B_00000040/extended_version.txt` wasn't deleted.

**Comment by kel00s** [comment] 2019-04-03 09:36
Thanks, 

Here are the debug log:

[wal-g-backup.log.gz](https://github.com/wal-g/wal-g/files/3037906/wal-g-backup.log.gz)

backup-list after backup-push
```
Path:
name                          last_modified        wal_segment_backup_start
base_000000010000017800000050 2019-04-02T11:45:41Z 000000010000017800000050
base_0000000100000179000000EB 2019-04-02T18:18:59Z 0000000100000179000000EB
base_000000010000017D00000076 2019-04-03T09:22:54Z 000000010000017D00000076
```

```
gsutil ls -l gs://gcs-bucket-wal/wal_005/
     79772  2019-04-03T09:18:04Z  gs://gcs-bucket-wal/wal_005/000000010000017D00000071.lz4
     79846  2019-04-03T09:19:04Z  gs://gcs-bucket-wal/wal_005/000000010000017D00000072.lz4
   3314390  2019-04-03T09:20:02Z  gs://gcs-bucket-wal/wal_005/000000010000017D00000073.lz4
   3016210  2019-04-03T09:20:12Z  gs://gcs-bucket-wal/wal_005/000000010000017D00000074.lz4
   2952060  2019-04-03T09:20:13Z  gs://gcs-bucket-wal/wal_005/000000010000017D00000075.lz4
       254  2019-04-03T09:22:54Z  gs://gcs-bucket-wal/wal_005/000000010000017D00000076.00000028.backup.lz4
   3177496  2019-04-03T09:21:14Z  gs://gcs-bucket-wal/wal_005/000000010000017D00000076.lz4
   2978386  2019-04-03T09:22:14Z  gs://gcs-bucket-wal/wal_005/000000010000017D00000077.lz4
    103981  2019-04-03T09:22:54Z  gs://gcs-bucket-wal/wal_005/000000010000017D00000078.lz4
    120133  2019-04-03T09:23:54Z  gs://gcs-bucket-wal/wal_005/000000010000017D00000079.lz4
   3319055  2019-04-03T09:24:02Z  gs://gcs-bucket-wal/wal_005/000000010000017D0000007A.lz4
   (...)
```

**Comment by CyberDem0n** [comment] 2019-04-03 09:43
@kel00s,

I think it would be more important to see the logs of `wal-g delete retain FULL ...`, because `backup-push` doesn't delete anything.

**Comment by kel00s** [comment] 2019-04-03 10:10
@CyberDem0n : sorry, not the right file. 

[wal-g-delete.log.gz](https://github.com/wal-g/wal-g/files/3038090/wal-g-delete.log.gz)

```
gsutil ls -l gs://<gcs-bucket>-wal/wal_005/
     79846  2019-04-03T10:06:03Z  gs://<gcs-bucket>-wal/wal_005/000000010000017F0000001B.lz4
     79846  2019-04-03T10:07:04Z  gs://<gcs-bucket>-wal/wal_005/000000010000017F0000001C.lz4
TOTAL: 2 objects, 159692 bytes (155.95 KiB)
```

```
envdir /etc/wal-e.d/env/ wal-g backup-list
Path:
name                          last_modified        wal_segment_backup_start
base_0000000100000179000000EB 2019-04-02T18:18:59Z 0000000100000179000000EB
base_000000010000017D00000076 2019-04-03T09:22:54Z 000000010000017D00000076
```

**Comment by x4m** [comment] 2019-04-03 17:47
It seems like it is a bug of GCS folder, it lists WALs with leading '/' when wals folder is in bucket root. I`m going to diagnose it better and fix tomorrow (UTC+5). Thanks for the report!

**Comment by g0djan** [comment] 2019-04-03 19:20
@CyberDem0n problem with "delete before" appears because parser fetches LSN from the backup name as "00000022000000020000004D_00000040" and it's bigger than "00000022000000020000004D" in wal-file. 
Right now only 2 variants of naming backup are expected for parser: 
- base_LSN 
- base_LSN1_D_LSN2. 
I'll look at this tomorrow(UTC +5) more detailed.

**Comment by g0djan** [comment] 2019-04-04 08:46
Fix for issue with "delete before"  was merged. Problem with `extended_version.txt` is known https://github.com/wal-g/wal-g/issues/201 and will be fixed with ending of refactoring delete handler.

**Comment by x4m** [comment] 2019-04-05 12:09
@kel00s please try latest pre-release, this problem should be fixed

**Comment by x4m** [comment] 2019-04-08 08:20
I'll close issue, on any sights of reappear - please ping me or repoen

**Closed by x4m** 2019-04-08 08:20 UTC
