### ISSUE TITLE
Unable to create a full basebackup with backup_push

### ISSUE THREAD

**Issue by lehni** [wal-g/wal-g#94] opened 2018-04-29 15:31 UTC
I've been using wal-e to successfully create backups of a  GitLab CE server to an S3 clone. I just tried to switch to wal-g, and while I managed to get it to talk to the S3 clone, it doesn't seem to upload a full backup.

Here the command I am running:
```sh
sudo -u gitlab-psql -s /bin/sh -c "envdir /etc/wal-g.d/env wal-g backup-push /var/opt/gitlab/postgresql/data"
```
And below its output.

It looks like part 1 is never finished, part 2 is omitted altogether, and only part 3 and part 4 get processed correctly, resulting in a tiny incomplete `basebackups_005` folder that contains only 219kb of data.

What am I doing wrong?

```sh
BUCKET: gitlab.*****.com
SERVER: wal-g
Walking ...
Starting part 1 ...

/PG_VERSION
/base
/base/1
[...]
/base/16385/PG_VERSION
/base/16385/pg_filenode.map
/base/16385/pg_internal.init
/global
/global/1136
[...]
/global/pg_filenode.map
/global/pg_internal.init
/pg_clog
/pg_clog/0000
/pg_commit_ts
/pg_dynshmem
/pg_hba.conf
/pg_ident.conf
/pg_logical
/pg_logical/mappings
/pg_logical/snapshots
/pg_multixact
/pg_multixact/members
/pg_multixact/members/0000
/pg_multixact/offsets
/pg_multixact/offsets/0000
/pg_notify
/pg_replslot
/pg_serial
/pg_snapshots
/pg_stat
/pg_stat_tmp
/pg_subtrans
/pg_tblspc
/pg_twophase
/pg_xlog
/postgresql.auto.conf
/postgresql.conf
/runtime.conf
/server.crt
/server.key
Starting part 3 ...
/global/pg_control
Finished writing part 3.
Starting part 4 ...
backup_label
tablespace_map
Finished writing part 4.
Uploaded 4 compressed tar Files.
```

**Comment by x4m** [comment] 2018-04-29 15:56
Hi! Which version do you use?

**Comment by lehni** [comment] 2018-04-29 16:28
I tried both v0.1.8 prebuilt and self-built from Github following the instructions in the README with the same result. Is there any additional information I shall provide?

**Comment by x4m** [comment] 2018-04-29 16:37
Ok, this may be a regression in v0.1.8..
May I ask you to try v0.1.7?

**Comment by lehni** [comment] 2018-04-29 16:48
That appears to work! But I'm getting 3 parts now, not 4, with a basebackup of around 12.5MB on disk:

```sh
Walking ...
Starting part 1 ...
/PG_VERSION
/base
/base/1
[...]
/base/16385/PG_VERSION
/base/16385/pg_filenode.map
/base/16385/pg_internal.init
/global
[...]
/global/pg_filenode.map
/global/pg_internal.init
/pg_clog
/pg_clog/0000
/pg_commit_ts
/pg_dynshmem
/pg_hba.conf
/pg_ident.conf
/pg_logical
/pg_logical/mappings
/pg_logical/snapshots
/pg_multixact
/pg_multixact/members
/pg_multixact/members/0000
/pg_multixact/offsets
/pg_multixact/offsets/0000
/pg_notify
/pg_replslot
/pg_serial
/pg_snapshots
/pg_stat
/pg_stat_tmp
/pg_subtrans
/pg_tblspc
/pg_twophase
/pg_xlog
/postgresql.auto.conf
/postgresql.conf
/runtime.conf
/server.crt
/server.key
Finished writing part 1.
Starting part 2 ...
/global/pg_control
Finished writing part 2.
Starting part 3 ...
backup_label
tablespace_map
Finished writing part 3.
Uploaded 3 compressed tar files.
```

**Comment by x4m** [comment] 2018-04-29 16:54
Well, that confirms a regression in 0.1.8...

About part numbers - yes, there is a numbering bug since very early versions. But it is just about giving the wrong number to part with pg_contorl, it does not lose data or something else, just one superfluous increment.

I need to reproduce this problem with 0.1.8 to fix it...

**Comment by lehni** [comment] 2018-04-29 16:58
I can provide the database if it's of use. There's not really any delicate information in there right now....

**Comment by x4m** [comment] 2018-04-29 17:05
I'd like to know OS, PostgreSQL version, hardware specs and what kind of S3 are you using.

**Comment by x4m** [comment] 2018-04-29 17:09
Well... I didn't asked most important thing. What kind of problem do you observe? Does it deadlock or something?

**Comment by lehni** [comment] 2018-04-29 17:16
OS: Linux CentOS 7.4 64-bit
PostgreSQL: 9.6 (Part of Gitlab installation, following these instructions: https://www.howtoforge.com/tutorial/how-to-install-and-configure-gitlab-ce-on-centos-7/)
S3 clone: 
https://www.exoscale.com/object-storage/
https://github.com/exoscale/pithos
Hardware:
Exoscale.com Small instance: 2 GB, 2 x 2198 MHz
```sh
cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel Xeon E3-12xx v2 (Ivy Bridge)
stepping	: 9
microcode	: 0x1
cpu MHz		: 2399.996
cache size	: 16384 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq vmx ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt arat
bogomips	: 4799.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
processor	: 1
[...]
```

**Comment by lehni** [comment] 2018-04-29 18:09
No, only 3 and 4 show up

**Comment by x4m** [comment] 2018-04-30 11:08
@lehni can I ask you to try code from the current master? I've improved code there

**Comment by lehni** [comment] 2018-04-30 11:33
Great! I will try it after lunch!

**Comment by lehni** [comment] 2018-04-30 12:15
Yay, that did it! Here's the end of my log:
```sh
/server.crt
/server.key
Finished writing part 1.
Starting part 2 ...
/global/pg_control
Finished writing part 2.
Starting part 3 ...
backup_label
tablespace_map
Finished writing part 3.
Uploaded 3 compressed tar Files.
```

**Comment by x4m** [comment] 2018-04-30 13:01
Cool! Thanks for your help!

**Comment by x4m** [comment] 2018-05-04 09:41
I'm closing this issue now. Feel free to open new issues on any sight of the problem, this makes backup software more reliable. Also we have Slack chat 
https://postgresteam.slack.com/messages/CA25P48P2

**Closed by x4m** 2018-05-04 09:41 UTC
