### ISSUE TITLE
wal archive with both wal-e and wal-g

### ISSUE THREAD

**Issue by carolfly86** [wal-g/wal-g#168] opened 2019-01-14 19:35 UTC
Hi, we are trying to migrate wal-e to wal-e with archive_command using script ```#!/bin/bash
/usr/bin/envdir /etc/wal-e.d/env /opt/wal-e/bin/wal-e wal-push $1 && \
/usr/bin/envdir /etc/wal-g.d/env /opt/wal-g/bin/wal-g wal-push $1 &>>/var/log/wal-g/wal-g.log```
Some wal files are archived by wal-g but are skipped by wal-e.
I think we ran into the same problem as https://github.com/wal-g/wal-g/issues/62 where `WAL-G will steal files from WAL-E`

is there any work around for this problem?

**Comment by x4m** [comment] 2019-01-15 04:13
Yes, we will fix it on WAL-G side here https://github.com/wal-g/wal-g/issues/127

But WAL-E will still steal from us...

**Comment by carolfly86** [comment] 2019-01-15 14:05
Thanks! I'll try that!

**Comment by carolfly86** [comment] 2019-01-15 15:43
Also, another question, could wal-g restore base backup and wal files archived by wal-e?

**Comment by x4m** [comment] 2019-01-15 16:07
Yes, we consider this as a supported feature. But you have to use lzo-enabled version (slightly bigger executable)

**Comment by carolfly86** [comment] 2019-01-15 16:17
Thanks! that's a great feature for wal-e to wal-g migration.

**Comment by x4m** [comment] 2019-01-22 09:53
@carolfly86 JFYI https://github.com/wal-g/wal-g/releases/tag/v0.2.4

**Comment by Tinsane** [comment] 2019-03-28 08:25
As this problem is a duplicate of #127, then we close it.

**Closed by Tinsane** 2019-03-28 08:25 UTC
