### ISSUE TITLE
wal-e and wal-g do, restore and see backups differently

### ISSUE THREAD

**Issue by DeathBorn** [wal-g/wal-g#175] opened 2019-01-28 11:58 UTC
- wal-g 0.2.4
- wal-e 1.1.0
- postgresql 11
- no load on db during backup operation

Backuping with *wal-g*
```
envdir /etc/patroni/patroni.env.d/ wal-g backup-push /data/psgtst
Path:  d1/lt/
INFO: 2019/01/28 12:43:42.352011 Doing full backup.
INFO: 2019/01/28 12:43:42.492948 Walking ...
INFO: 2019/01/28 12:43:42.493264 Starting part 1 ...
INFO: 2019/01/28 12:43:48.964679 Finished writing part 1.
INFO: 2019/01/28 12:43:49.097461 Starting part 2 ...
INFO: 2019/01/28 12:43:49.097815 /global/pg_control
INFO: 2019/01/28 12:43:49.118848 Finished writing part 2.
INFO: 2019/01/28 12:43:50.157042 Starting part 3 ...
INFO: 2019/01/28 12:43:50.163297 backup_label
INFO: 2019/01/28 12:43:50.163337 tablespace_map
INFO: 2019/01/28 12:43:50.163395 Finished writing part 3.
INFO: 2019/01/28 12:43:50.208995 Uploaded 3 compressed tar Files.
```

Then running backup operation with *wal-e*
```
envdir /etc/patroni/patroni.env.d/ wal-e backup-push /data/psgtst
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-push".
        STRUCTURED: time=2019-01-28T11:44:39.951811-00 pid=30875
wal_e.operator.backup INFO     MSG: start upload postgres version metadata
        DETAIL: Uploading to s3://psgtst/d1/lt/basebackups_005/base_000000090000000200000086_00000040/extended_version.txt.
        STRUCTURED: time=2019-01-28T11:44:40.555383-00 pid=30875
wal_e.operator.backup INFO     MSG: postgres version metadata upload complete
        STRUCTURED: time=2019-01-28T11:44:40.607858-00 pid=30875
wal_e.worker.upload INFO     MSG: beginning volume compression
        DETAIL: Building volume 0.
        STRUCTURED: time=2019-01-28T11:44:41.088372-00 pid=30875
wal_e.worker.upload INFO     MSG: begin uploading a base backup volume
        DETAIL: Uploading to "s3://psgtst/d1/lt/basebackups_005/base_000000090000000200000086_00000040/tar_partitions/part_00000000.tar.lzo".
        STRUCTURED: time=2019-01-28T11:44:43.779875-00 pid=30875
wal_e.worker.upload INFO     MSG: finish uploading a base backup volume
        DETAIL: Uploading to "s3://psgtst/d1/lt/basebackups_005/base_000000090000000200000086_00000040/tar_partitions/part_00000000.tar.lzo" complete at 71405.8KiB/s.
        STRUCTURED: time=2019-01-28T11:44:44.722630-00 pid=30875
NOTICE:  pg_stop_backup complete, all required WAL segments have been archived
```
### Problem 1: Wal-g sees everything, but in different format
```
envdir /etc/patroni/patroni.env.d/ wal-g backup-list
Path:  d1/lt/
name                                   last_modified        wal_segment_backup_start
base_000000090000000200000084          2019-01-28T11:43:50Z 000000090000000200000084
base_000000090000000200000086_00000040 2019-01-28T11:44:45Z 000000090000000200000086_00000040
```
While wal-e can't see wal-g backups
```
envdir /etc/patroni/patroni.env.d/ wal-e backup-list
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-list".
        STRUCTURED: time=2019-01-28T11:51:05.224447-00 pid=32765
name	last_modified	expanded_size_bytes	wal_segment_backup_start	wal_segment_offset_backup_start	wal_segment_backup_stop	wal_segment_offset_backup_stop
base_000000090000000200000086_00000040	2019-01-28T11:44:45.813Z		000000090000000200000086	00000040
```

### Problem 2: wal-e backup is restored diferently by wal-e and wal-g
```
ls -l wal_e_restored_by_wal_e/:
total 152
backup_label
base
current_logfiles
global
patroni.dynamic.json
pg_commit_ts
pg_dynshmem
pg_hba.conf.backup
pg_ident.conf.backup
pg_log
pg_logical
pg_multixact
pg_notify
pg_replslot
pg_serial
pg_snapshots
pg_stat
pg_stat_tmp
pg_subtrans
pg_tblspc
pg_twophase
PG_VERSION
pg_wal -> /wal/psgtst
pg_xact
postgresql.auto.conf
postgresql.base.conf
postgresql.base.conf.backup
postgresql.conf.backup

ls -l wal_e_restored_by_wal_g/:
total 72
backup_label
base
global
pg_commit_ts
pg_dynshmem
pg_log
pg_logical
pg_multixact
pg_notify
pg_replslot
pg_serial
pg_snapshots
pg_stat
pg_stat_tmp
pg_subtrans
pg_tblspc
pg_twophase
pg_wal -> pg_wal
pg_xact
```
Also pg_wal symlink is not restored correctly on wal-g

```
ls -l wal_g_restored_by_wal_g/:
total 172
backup_label
base
current_logfiles
global
patroni.dynamic.json
pg_commit_ts
pg_dynshmem
pg_hba.conf
pg_hba.conf.backup
pg_ident.conf
pg_ident.conf.backup
pg_log
pg_logical
pg_multixact
pg_notify
pg_replslot
pg_serial
pg_snapshots
pg_stat
pg_stat_tmp
pg_subtrans
pg_tblspc
pg_twophase
PG_VERSION
pg_xact
postgresql.auto.conf
postgresql.base.conf
postgresql.base.conf.backup
postgresql.conf
postgresql.conf.backup
recovery.done
tablespace_map
```

**Comment by x4m** [comment] 2019-01-29 06:08
Hi! Thanks for reporting!

Looks the same as #172 

Can you plz give me backup?

**Comment by DeathBorn** [comment] 2019-01-29 07:08
How blind of me! Give me some time to prepare them without sensitive info.

**Comment by x4m** [comment] 2019-01-29 17:21
Actually, I think it's not necessary to do a backup of your full db. Just an empty (fresh initdb) in your environment, probably, will be enough to troubleshoot the problem.

**Comment by fdr** [comment] 2019-02-03 06:05
This was not intended to be a feature: WAL-G's storage format is more streamlined than WAL-E, and can read, and not write, archives compatible with WAL-E. It was intended to be a one-way transition only.

**Comment by x4m** [comment] 2019-02-20 13:03
Please test that issue is fixed in the recent version. If something is still broken plz reopen.

**Closed by x4m** 2019-02-20 13:03 UTC
