### ISSUE TITLE
wal-g wal-push can deadlock when WALG_UPLOAD_CONCURRENCY is higher than 1

### ISSUE THREAD

**Issue by brouberol** [wal-g/wal-g#222] opened 2019-03-26 07:47 UTC
Affected version: `v0.1.12`

This bug does not manifest itself at every run, but creeps up every so often in production. When running wal-g with `WALG_UPLOAD_CONCURRENCY=8`, we're seeing a blocked `wal-g wal-push` process.

Sending a `SIGHUP` signal displays the following goroutine stacktraces

```
goroutine 0 [idle]:
runtime.futex(0xf27068, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffeb272a008, 0x41a57b, ...)
       /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/runtime/sys_linux_amd64.s:530 +0x21
runtime.futexsleep(0xf27068, 0x7ffe00000000, 0xffffffffffffffff)
       /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/runtime/os_linux.go:45 +0x4b
runtime.notesleep(0xf27068)
       /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/runtime/lock_futex.go:151 +0x9b
runtime.stopm()
       /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/runtime/proc.go:1952 +0xe5
runtime.findrunnable(0xc42004a000, 0x0)
       /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/runtime/proc.go:2415 +0x50c
runtime.schedule()
       /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/runtime/proc.go:2541 +0x13b
runtime.park_m(0xc42028d380)
       /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/runtime/proc.go:2604 +0xb6
runtime.mcall(0x8ee6f0)
       /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/runtime/asm_amd64.s:351 +0x5b

goroutine 1 [semacquire, 8 minutes]:
sync.runtime_Semacquire(0xc42026e264)
       /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc42026e258)
       /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/sync/waitgroup.go:129 +0x72
github.com/wal-g/wal-g.(*BgUploader).Stop(0xc42026e240)
       /home/travis/gopath/src/github.com/wal-g/wal-g/bguploader.go:70 +0x8b
github.com/wal-g/wal-g.HandleWALPush(0xc4202b4480, 0x7ffeb272bce1, 0x20, 0xc420286150, 0x0)
       /home/travis/gopath/src/github.com/wal-g/wal-g/commands.go:601 +0xdc
main.main()
       /home/travis/gopath/src/github.com/wal-g/wal-g/cmd/wal-g/main.go:136 +0x70f

goroutine 83 [semacquire, 8 minutes]:
sync.runtime_SemacquireMutex(0xc42026e280, 0xc4202c8100)
       /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc42026e27c)
       /home/travis/.gimme/versions/go1.10.8.linux.amd64/src/sync/mutex.go:134 +0x108
github.com/wal-g/wal-g.scanOnce(0xc42026e240)
       /home/travis/gopath/src/github.com/wal-g/wal-g/bguploader.go:78 +0x4e
github.com/wal-g/wal-g.(*BgUploader).Upload(0xc42026e240, 0xa97480, 0xc42c88c5b0)
       /home/travis/gopath/src/github.com/wal-g/wal-g/bguploader.go:130 +0x502
created by github.com/wal-g/wal-g.scanOnce
       /home/travis/gopath/src/github.com/wal-g/wal-g/bguploader.go:103 +0x349
```

It seems we're blocked acquiring a mutex that might not have been properly released.

For reference, we run wal-g with the following environment variables

```
WALG_S3_SSE=AES256
WALG_DOWNLOAD_CONCURRENCY=64
WALG_UPLOAD_DISK_CONCURRENCY=2
WALG_UPLOAD_CONCURRENCY=8
```

We've observed that setting `WALG_UPLOAD_CONCURRENCY` to 1 unblocks the `wal-g wal-push` process.

**Comment by x4m** [comment] 2019-03-26 08:14
Thanks for reporting! These stacks are very helpful, I'll review this and provide more information.

BTW, v0.1.12 has some other bugs since that prerelease, current release for branch 0.1 is v0.1.16

**Comment by x4m** [comment] 2019-03-26 08:22
Yes, there is deadlock and it seems like current versions are still affected. Working on fix.

**Comment by brouberol** [comment] 2019-03-26 08:24
Thanks for reaching back so quickly! Let me know if there's anything I can do to help.

**Comment by x4m** [comment] 2019-03-27 08:49
@brouberol can I ask you to try #223 ?
I can create draft release forked from any version for test purposes.

**Comment by x4m** [comment] 2019-03-27 09:06
We never encountered the problem, because we used external timeout as atavism from WAL-E usage. But eventually, we should get rid of it.

**Comment by Aevin1387** [comment] 2019-03-27 16:04
@x4m If you generate a draft release from v0.1.16, we'd definitely be able to put it in place on the system we are seeing this issue in. We've seen it twice in the past two weeks and a potential fix would be helpful.

**Comment by x4m** [comment] 2019-03-27 16:43
@Aevin1387 https://github.com/wal-g/wal-g/releases/tag/v0.1.17

**Comment by x4m** [comment] 2019-04-04 09:23
@Aevin1387 @brouberol any news? Does this work as expected?

**Comment by Aevin1387** [comment] 2019-04-06 00:39
@x4m It took a while for it to re-appear, but I can confirm that this fixes the race condition we were seeing.

**Comment by x4m** [comment] 2019-04-08 08:22
I'll close this, looks like fixed. Please report on any suspicious events from WAL-G.

**Closed by x4m** 2019-04-08 08:22 UTC
